name: Build Release

on:  
  push:
    tags:
      - 'v*'

jobs:
  create_release:
      name:  Create Release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Create Release
          id: create_release
          uses: elgohr/Github-Release-Action@v4
          env:
            GITHUB_TOKEN: ${{ github.token }}
          with:
            title: ${{ github.ref }}
        - name: Upload install.bat
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: install.bat
            asset_name: install.bat
            tag: ${{ github.ref }}
            overwrite: true
  publish_binaries:
    name: Release Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build and Publish
      uses: wangyoucao577/go-release-action@v1.28
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: codegame
        asset_name: codegame-cli-${{matrix.goos}}-${{matrix.goarch}}
        extra_files: LICENSE README.md
        release_tag: ${{ github.ref }}
        ldflags: -X "main.version=${{ github.ref }}"
        md5sum: false
